---
title: "Power_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Load packages
library(data.table)
library(ggplot2)
library(gridExtra)
```

Find an article that shows males and older individuals are more right leaning.
Vary the treatment effect size.
https://www.pewresearch.org/fact-tank/2020/04/01/americans-main-sources-for-political-news-vary-by-party-and-age/

```{r}
# This will hold true for all simulations.
estimated_sample_size <- 126
```


```{r}
CreateData <- function(sample_size, y0, tau_male, tau_female, tau_old, 
                       tau_facebook) {
  #' Creates a simulation of the expected data from the experiment given the
  #' estimated tau distributions and sample size.
  #' 
  #' Args:
  #'  sample_size: The desired number of samples for the output data.
  #'  y0: Normal distribution of the effect of being 20-29 years old and of a non-
  #'    specified gender has on the bias of news media presented on YouTube.
  #'    gender
  #'  tau_male: Normal distribution of the effect of identifying as male has on
  #'    the bias of news media presented on YouTube.
  #'  tau_female: Normal distribution of the effect of identifying as female has
  #'    on the bias of news media presented on YouTube.
  #'  tau_old: Normal distribution of the effect of being 60-69 years old has on
  #'    the bias of news media presented on YouTube.
  #'  tau_facebook: Normal distribution of the effect being on Facebook has on
  #'    the bias of the news media presented.
  #'    
  #' Returns:
  #'  d: A data table of the simulated experiment data.

  d <- data.table(id = 1:sample_size) 
  d[ , ':='(
    y0 = y0,
    tau_male = tau_male, 
    tau_female = tau_female, 
    tau_old = tau_old,
    tau_facebook = tau_facebook
  )]
  
  all_group_combos <- c(
    'na-young-facebook',
    'na-old-facebook',
    'male-young-facebook',
    'male-old-facebook',
    'female-young-facebook',
    'female-old-facebook',
    'na-young-youtube',
    'na-old-youtube',
    'male-young-youtube',
    'male-old-youtube',
    'female-young-youtube',
    'female-old-youtube'
  )
  
  d[ , treat_condition := sample(c(all_group_combos), size = .N, replace = TRUE)]
  
  d[treat_condition == 'na-young-facebook', ':=' (avg_bias = y0 + tau_facebook, 
                                                  is_male=0, 
                                                  is_female=0, 
                                                  is_old=0, 
                                                  is_facebook=1)]
  d[treat_condition == 'na-old-facebook', ':=' (avg_bias = y0 + tau_old + tau_facebook, 
                                                is_male=0, 
                                                is_female=0, 
                                                is_old=1, 
                                                is_facebook=1)]
  d[treat_condition == 'male-young-facebook', ':=' (avg_bias = y0 + tau_male + tau_facebook, 
                                                    is_male=1, 
                                                    is_female=0, 
                                                    is_old=0, 
                                                    is_facebook=1)]
  d[treat_condition == 'male-old-facebook', ':=' (avg_bias = y0 + tau_male + tau_old + tau_facebook, 
                                                  is_male=1, 
                                                  is_female=0, 
                                                  is_old=1, 
                                                  is_facebook=1)]
  d[treat_condition == 'female-young-facebook', ':=' (avg_bias = y0 + tau_female + tau_facebook, 
                                                      is_male=0, 
                                                      is_female=1, 
                                                      is_old=0, 
                                                      is_facebook=1)]
  d[treat_condition == 'female-old-facebook', ':=' (avg_bias = y0 + tau_female + tau_old + tau_facebook, 
                                                    is_male=0, 
                                                    is_female=1, 
                                                    is_old=1, 
                                                    is_facebook=1)]
  d[treat_condition == 'na-young-youtube', ':=' (avg_bias = y0, 
                                                 is_male=0, 
                                                 is_female=0, 
                                                 is_old=0, 
                                                 is_facebook=0)]
  d[treat_condition == 'na-old-youtube', ':=' (avg_bias = y0 + tau_old, 
                                               is_male=0, 
                                               is_female=0, 
                                               is_old=1, 
                                               is_facebook=0)]
  d[treat_condition == 'male-young-youtube', ':=' (avg_bias = y0 + tau_male, 
                                                   is_male=1, 
                                                   is_female=0, 
                                                   is_old=0, 
                                                   is_facebook=0)]
  d[treat_condition == 'male-old-youtube', ':=' (avg_bias = y0 + tau_male + tau_old, 
                                                 is_male=1, 
                                                 is_female=0, 
                                                 is_old=1, 
                                                 is_facebook=0)]
  d[treat_condition == 'female-young-youtube', ':=' (avg_bias = y0 + tau_female, 
                                                     is_male=0, 
                                                     is_female=1, 
                                                     is_old=0, 
                                                     is_facebook=0)]
  d[treat_condition == 'female-old-youtube',   ':=' (avg_bias = y0 + tau_female + tau_old, 
                                                     is_male=0, 
                                                     is_female=1, 
                                                     is_old=1, 
                                                     is_facebook=0)]
  
  return_columns <- c('is_male', 'is_female', 'is_old', 'is_facebook', 'avg_bias')
  return(d[ , ..return_columns])
}
```


```{r}
SimulatePower <- function(experiment_data){
  #' Collects 1,000 p-values for each percentage of sample size taken from the
  #' experiment data.
  #' 
  #' Args:
  #'  experiment_data: The simulated data collected from the experiment.
  #'  
  #' Returns:
  #'  res: A dataframe containing the power of each sample percentage for each
  #'    covariate.
  # Defining the percentage as a sequence starting at 0.1 to 2, step size = 0.1
  percentages_to_sample <- seq(0.1, 2, by=0.1)
  
  # To store the power of each simulation.
  intercept_powers <- rep(NA, length(percentages_to_sample))
  is_male_powers <- rep(NA, length(percentages_to_sample))
  is_female_powers <- rep(NA, length(percentages_to_sample))
  is_old_powers <- rep(NA, length(percentages_to_sample))
  is_facebook_powers <- rep(NA, length(percentages_to_sample))
  
  j <- 1
  for (p in percentages_to_sample) {
    
    # To store the p-values for this simulation.
    intercept_p_values <- rep(NA, 1000)
    is_male_p_values <- rep(NA, 1000)
    is_female_p_values <- rep(NA, 1000)
    is_old_p_values <- rep(NA, 1000)
    is_facebook_p_values <- rep(NA, 1000)
    for (i in 1:1000) {
      sampled_data <- experiment_data[
        experiment_data[ , .(sample(.I, size = .N * p, replace = TRUE))]$V1]
      model <- lm(avg_bias ~ is_male + is_female + is_old + is_facebook, sampled_data)
      
      intercept_p_values[i] <- summary(model)$coefficients[,4][1]
      is_male_p_values[i] <- summary(model)$coefficients[,4][2]
      is_female_p_values[i] <- summary(model)$coefficients[,4][3]
      is_old_p_values[i] <- summary(model)$coefficients[,4][4]
      is_facebook_p_values[i] <- summary(model)$coefficients[,4][5]
    }
    # Storing the power of this simulation.
    intercept_powers[j] <- length(intercept_p_values[intercept_p_values <= 0.05]
                            ) / length(intercept_p_values)
    is_male_powers[j] <- length(is_male_p_values[is_male_p_values <= 0.05]
                                ) / length(is_male_p_values)
    is_female_powers[j] <- length(is_female_p_values[is_female_p_values <= 0.05]
                                  ) / length(is_female_p_values)
    is_old_powers[j] <- length(is_old_p_values[is_old_p_values <= 0.05]
                               ) / length(is_old_p_values)
    is_facebook_powers[j] <- length(is_facebook_p_values[is_facebook_p_values <= 0.05]
                                    ) / length(is_facebook_p_values)
    
    j <- j + 1
  }
  
  # Combining results into a data frame.
  res <- data.frame(percentages_to_sample, intercept_powers, is_male_powers,
                    is_female_powers, is_old_powers, is_facebook_powers)
  return(res)
}
```


# Low Treatment Effect
```{r}
y0 <- rnorm(estimated_sample_size, mean = 0, sd = 3)
tau_male <- rnorm(estimated_sample_size, mean = 3, sd = 3)
tau_female <- rnorm(estimated_sample_size, mean = -1, sd = 3)
tau_old <- rnorm(estimated_sample_size, mean = 2, sd = 3)
tau_facebook <- rnorm(estimated_sample_size, mean = -1, sd = 3) 

experiment_data <- CreateData(estimated_sample_size, y0, tau_male, tau_female, tau_old, tau_facebook)

low_effect <- SimulatePower(experiment_data)
```

# Regular Treatment Effect
```{r}
y0 <- rnorm(estimated_sample_size, mean = 0, sd = 3)
tau_male <- rnorm(estimated_sample_size, mean = 5, sd = 3)
tau_female <- rnorm(estimated_sample_size, mean = -3, sd = 3)
tau_old <- rnorm(estimated_sample_size, mean = 4, sd = 3)
tau_facebook <- rnorm(estimated_sample_size, mean = -3, sd = 3) 

experiment_data <- CreateData(estimated_sample_size, y0, tau_male, tau_female, tau_old, tau_facebook)

regular_effect <- SimulatePower(experiment_data)
```

# Large Treatment Effect
```{r}
y0 <- rnorm(estimated_sample_size, mean = 0, sd = 3)
tau_male <- rnorm(estimated_sample_size, mean = 7, sd = 3)
tau_female <- rnorm(estimated_sample_size, mean = -5, sd = 3)
tau_old <- rnorm(estimated_sample_size, mean = 6, sd = 3)
tau_facebook <- rnorm(estimated_sample_size, mean = -5, sd = 3) 

experiment_data <- CreateData(estimated_sample_size, y0, tau_male, tau_female, tau_old, tau_facebook)

large_effect <- SimulatePower(experiment_data)
```

# Sample Size and Power
```{r}
low_effect$Effect <- 'Low'
regular_effect$Effect <- 'Regular'
large_effect$Effect <- 'Large'
data <- rbind(low_effect, regular_effect, large_effect)

is_male <- ggplot(data = data, aes(x=percentages_to_sample*estimated_sample_size, y=is_male_powers*100)) + geom_line(aes(colour=Effect)) + xlab("Sample Size") + ylab("Power") + labs(title = "Male") + theme(plot.title = element_text(hjust = 0.5))
is_female <- ggplot(data = data, aes(x=percentages_to_sample*estimated_sample_size, y=is_female_powers*100)) + geom_line(aes(colour=Effect)) + xlab("Sample Size") + ylab("Power") + labs(title = "Female") + theme(plot.title = element_text(hjust = 0.5))
is_old <- ggplot(data = data, aes(x=percentages_to_sample*estimated_sample_size, y=is_old_powers*100)) + geom_line(aes(colour=Effect)) + xlab("Sample Size") + ylab("Power") + labs(title = "Old") + theme(plot.title = element_text(hjust = 0.5))
is_facebook <- ggplot(data = data, aes(x=percentages_to_sample*estimated_sample_size, y=is_facebook_powers*100)) + geom_line(aes(colour=Effect)) + xlab("Sample Size") + ylab("Power") + labs(title = "Facebook") + theme(plot.title = element_text(hjust = 0.5))
plot_list <- list(is_male, is_female, is_old, is_facebook)
grid.arrange(is_male, is_female, is_old, is_facebook, nrow=2,top=("Relationship between Sample Size and Power"))
```
