---
title: "Regression Model"
author: 'W241: Fox, George, McCleary'
date: "7/27/2022"
output: pdf_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
library(dplyr)
library(readxl)
library(ggplot2)
library(tidyr)
library(stringi)
library(sandwich)
library(lmtest)
library(stargazer)
```

# Load and Merge Data
```{r, include=TRUE}
final_data_hannah <- readxl::read_xlsx("w241 Final Project Data_Final.xlsx", sheet = 2, n_max = 85)
final_data_allison <- readxl::read_xlsx("w241 Final Project Data_Final.xlsx", sheet = 3, n_max = 85)
final_data_carlie <- readxl::read_xlsx("w241 Final Project Data_Final.xlsx", sheet = 4, n_max = 85)
final_data_carlie <- final_data_carlie[,c(1:51)]
final_data <- rbind(final_data_hannah, final_data_allison, final_data_carlie)
```


# Clean data
```{r, warning = FALSE, include=TRUE}
# pivot longer
final_data_long <- final_data[,c(1:8,45,47)] %>% pivot_longer(cols = c(`Average Bias`, `Average Reliability`), 
                                          names_to = 'Metric', values_to = 'Value')

# convert variable types
final_data_long$Value <- as.numeric(final_data_long$Value)
final_data_long$Website <- as.factor(final_data_long$Website)
final_data_long$Metric <- as.factor(final_data_long$Metric)

# update sample ID from email address since its not reading in properly
final_data_long$`Sample ID` <- stringi::stri_sub(final_data_long$`GMail Address`, 18, 20)
```


# Create Covariates
```{r, include=TRUE}
final_data_long$is_male <- ifelse(final_data_long$Gender == "Male", 1, 0)
final_data_long$is_female <- ifelse(final_data_long$Gender == "Female", 1, 0)
final_data_long$is_old <- ifelse(final_data_long$`Age Group` == "Old", 1, 0)
final_data_long$is_facebook <- ifelse(final_data_long$Website == "Facebook", 1, 0)
```

# Create Complete Cases Dataset
```{r, include=TRUE}
# create the dataset of only the accounts for which we have Facebook and YouTube
final_data_long_filt <- final_data_long %>% 
  dplyr::filter(is.na(Value) == FALSE)
final_data_long_filt <- final_data_long_filt %>%
  dplyr::group_by(final_data_long_filt$`GMail Address`) %>% 
  dplyr::filter(n() > 2)
```



# Run Bias Models
```{r}
# bias model with no covariates
bias_model_short <- lm(Value ~ is_male + is_female + is_old + is_facebook, 
                   final_data_long %>% filter(Metric == "Average Bias"))
coef <- coeftest(bias_model_short, vcov. = vcovHC(bias_model_short))
coef
```

```{r}
# bias model with covariates
bias_model_long <- lm(Value ~ is_male + is_female + is_old + is_facebook + as.factor(`Due Date`) +
                   as.factor(Researcher), 
                   final_data_long %>% filter(Metric == "Average Bias"))
coef <- coeftest(bias_model_long, vcov. = vcovHC(bias_model_long))
coef
```


```{r}
# bias model with only complete observations
bias_model_filt <- lm(Value ~ is_male + is_female + is_old + is_facebook + as.factor(`Due Date`) +
                   as.factor(Researcher), 
                   final_data_long_filt %>% filter(Metric == "Average Bias"))
coef <- coeftest(bias_model_filt, vcov. = vcovHC(bias_model_filt))
coef
```


# Run Reliability Models
```{r}
# reliability model with no covariates
reliability_model_short <- lm(Value ~ is_male + is_female + is_old + is_facebook, 
                   final_data_long %>% filter(Metric == "Average Reliability"))
coef <- coeftest(reliability_model_short, vcov. = vcovHC(reliability_model_short))
coef
```

```{r}
# reliability model with covariates
reliability_model_long <- lm(Value ~ is_male + is_female + is_old + is_facebook + as.factor(`Due Date`) +
                   as.factor(Researcher), 
                   final_data_long %>% filter(Metric == "Average Reliability"))
coef <- coeftest(reliability_model_long, vcov. = vcovHC(reliability_model_long))
coef
```


```{r}
# reliability model with only complete observations
reliability_model_filt <- lm(Value ~ is_male + is_female + is_old + is_facebook + as.factor(`Due Date`) +
                   as.factor(Researcher), 
                   final_data_long_filt %>% filter(Metric == "Average Reliability"))
coef <- coeftest(reliability_model_filt, vcov. = vcovHC(reliability_model_filt))
coef
```


# Stargazer Outputs for Bias Models
```{r, warning=FALSE, results='asis'}
stargazer(bias_model_short, bias_model_long, bias_model_filt, 
          title = "Average Bias Regression Models", header = FALSE)
```

# Stargazer Outputs for Reliability Models
```{r, warning=FALSE, results='asis'}
stargazer(reliability_model_short, reliability_model_long, reliability_model_filt, 
          title = "Average Reliability Regression Models", header = FALSE)
```

