---
title: "Visualization"
author: 'W241: Fox, George, McCleary'
date: "7/7/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(dplyr)
library(readxl)
library(ggplot2)
library(tidyr)
```

# Load Clean Data
```{r}
final_data_clean <- data.table(readxl::read_xlsx("Final_Data_clean.xlsx"))
source_data <- data.table(readxl::read_xlsx("Source_Counts_Output.xlsx", sheet=1))
source_data_youtube <- data.table(readxl::read_xlsx("Source_Counts_Output.xlsx", sheet=2))
source_data_facebook <- readxl::read_xlsx("Source_Counts_Output.xlsx", sheet=3)
source_data_youtube[Source=="CBS Evening News with Nora O'Donnell", Source:="CBS Evening News"]
final_data_clean
```


# Plot average bias and reliability of sources
```{r, warning = FALSE} 
d_reliability <- final_data_clean[Metric == 'Average Reliability']
d_bias <- final_data_clean[Metric == 'Average Bias']

ggplot(d_bias, aes(fill = Website, y = Value, x = Metric)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average Bias of News Sources on Facebook and Youtube") +
  xlab("")+
  scale_y_continuous(limits = c(-10,10), breaks = c(-10,0,10,20,30,40)) + coord_flip()

ggplot(d_reliability, aes(fill = Website, y = Value, x = Metric)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average Reliability of News Sources on Facebook and Youtube") +
  xlab("")+
  scale_y_continuous(limits = c(0,50), breaks = c(-10,0,10,20,30,40)) + coord_flip()
```
```{r, warning = FALSE} 
d_reliability <- final_data_clean[Metric == 'Average Reliability']
d_bias <- final_data_clean[Metric == 'Average Bias']

ggplot(d_bias, aes(x = Value, color = Website, fill = Website)) + 
  geom_density(alpha=0.8) + 
  labs(title = "Density of Average Bias of News Sources on Facebook and Youtube") +
  ylab("Density") +
  xlab("Average Bias") +
  scale_color_manual(values=c("#4c948c", "#bc7c3c")) +
  scale_fill_manual(values=c("#4c948c", "#bc7c3c"))
```
```{r}
ggplot(d_reliability, aes(x = Value, color = Website, fill = Website)) + 
  geom_density(alpha=0.8) + 
  labs(title = "Density of Average Reliability of News Sources on Facebook and Youtube") +
  ylab("Density") +
  xlab("Average Reliability") +
  scale_color_manual(values=c("#4c948c", "#bc7c3c")) +
  scale_fill_manual(values=c("#4c948c", "#bc7c3c"))
```


```{r, warning = FALSE} 
#Subset data to bias metrics
bias_data <- filter(final_data_clean, Metric == 'Average Bias')

#Plot average bias by Gender 
ggplot(bias_data, aes(fill = Website, y = Value, x = Gender)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average News Source Bias on Facebook and Youtube by Gender") +
  scale_y_continuous(limits = c(-5,5), breaks = c(-5,0,5))

```

```{r}
ggplot(d_bias, aes(x = Value, color = Gender, fill = Gender)) + 
  geom_density(alpha=0.6) + 
  labs(title = "Density of Average Bias of News Sources by Gender") +
  ylab("Density") +
  xlab("Average Bias") +
  scale_color_manual(values=c("#3c5c5c", "#d1a343", '#8b2832')) +
  scale_fill_manual(values=c("#3c5c5c", "#d1a343", '#8b2832'))
```
```{r}
ggplot(d_reliability, aes(x = Value, color = Gender, fill = Gender)) + 
  geom_density(alpha=0.6) + 
  labs(title = "Density of Average Reliability of News Sources by Gender") +
  ylab("Density") +
  xlab("Average Reliability") +
  scale_color_manual(values=c("#3c5c5c", "#d1a343", '#8b2832')) +
  scale_fill_manual(values=c("#3c5c5c", "#d1a343", '#8b2832'))
```

```{r}
ggplot(d_bias, aes(x = Value, color = `Age Group`, fill = `Age Group`)) + 
  geom_density(alpha=0.7) + 
  labs(title = "Density of Average Bias of News Sources by Age") +
  ylab("Density") +
  xlab("Average Bias") +
  scale_color_manual(values=c("#8b2832", "#3c5d5b")) +
  scale_fill_manual(values=c("#8b2832", "#3c5d5b"))
```

```{r}
ggplot(d_reliability, aes(x = Value, color = `Age Group`, fill = `Age Group`)) + 
  geom_density(alpha=0.7) + 
  labs(title = "Density of Average Reliability of News Sources by Age") +
  ylab("Density") +
  xlab("Average Reliability") +
  scale_color_manual(values=c("#8b2832", "#3c5d5b")) +
  scale_fill_manual(values=c("#8b2832", "#3c5d5b"))
```

```{r, warning = FALSE} 
#Plot average bias by age
ggplot(bias_data, aes(fill = Website, y = Value, x = `Age Group`)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average News Source Bias on Facebook and Youtube by Age") +
  scale_y_continuous(limits = c(-5,5), breaks = c(-5,0,5))
```

```{r, warning = FALSE} 
#Subset data to reliability metrics
reliability_data <- filter(final_data_clean, Metric == 'Average Reliability')

#Plot avg reliability by gender
ggplot(reliability_data, aes(fill = Website, y = Value, x = Gender)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average News Source Reliability on Facebook and Youtube by Gender") +
  scale_y_continuous(limits = c(-10,60), breaks = c(-10,0,10,20,30,40,50,60))
```
```{r, warning = FALSE} 
#Plot avg reliability by age
ggplot(reliability_data, aes(fill = Website, y = Value, x = `Age Group`)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'mean') + 
  labs(title = "Average News Source Reliability on Facebook and Youtube by Gender") +
  scale_y_continuous(limits = c(-10,60), breaks = c(-10,0,10,20,30,40,50,60))
```
```{r}
#Subset data to bias dataset so only one row per account
blocked_accounts <- filter(bias_data, is.na(Value))

#Plot count of blocked accounts by age and gender
blocked_accounts <- blocked_accounts %>% mutate(row_count=1)

ggplot(blocked_accounts, aes(fill = Website,y = row_count, x = `Age Group`)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'sum') + 
  labs(title = "Histogram of Blocked Facebook Accounts by Age") +
  scale_y_continuous(limits = c(0,40), breaks = c(0,10,20,30,40))

```

```{r}
#Blocked facebook accounts by gender
ggplot(blocked_accounts, aes(fill = Website,y = row_count, x = Gender)) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'sum') + 
  labs(title = "Histogram of Blocked Facebook Accounts by Gender") +
  scale_y_continuous(limits = c(0,30), breaks = c(0,10,20,30))
```
  
```{r}
#Line graph of block accounts over time
blocked_sum <- blocked_accounts %>% count(`Due Date`, row_count)

ggplot(blocked_sum, aes(x=`Due Date`, y=n, group=1)) +
  geom_line()+
  geom_point()+labs(title = "Blocked Facebook Accounts over Time") + ylab("Count of Blocked Accounts")
```
```{r}
sources_top <- source_data %>% slice(1:10)

plot1 <- ggplot(sources_top, aes(fill = `bias label`,y = Count, x = reorder(Source, Count))) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'sum') + 
  labs(title = "Top News Sources", fill="Bias Label") +
  scale_y_continuous(limits = c(0,175), breaks = c(0,50,100,150)) + coord_flip()

plot1 + scale_fill_manual(breaks = c("Skews Right", "Skews Left", "Middle"), 
                       values=c("#8b2832", "#3c5d5b", "#d1a343"))+ xlab("Sources")
```
```{r}
#Facebook top sources
sources_top_fb <- source_data_facebook %>% slice(1:10)

plot2 <- ggplot(sources_top_fb, aes(fill = `bias label`,y = Count, x = reorder(Source, Count))) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'sum') + 
  labs(title = "Top Facebook News Sources", fill="Bias Label") +
  scale_y_continuous(limits = c(0,100), breaks = c(0,50,100)) + coord_flip()
plot2 + scale_fill_manual(breaks = c("Skews Right", "Skews Left", "Middle"), 
                       values=c("#8b2832", "#3c5d5b", "#d1a343"))+ xlab("Sources")
```
  
```{r}
#Google top sources
sources_top_yt <- source_data_youtube %>% slice(1:10)

plot3 <- ggplot(sources_top_yt, aes(fill = `bias label`,y = Count, x = reorder(Source, Count))) + 
  geom_bar(position = 'dodge', stat = 'summary', fun = 'sum') + 
  labs(title = "Top Youtube News Sources", fill="Bias Label") + 
  scale_y_continuous(limits = c(0,150), breaks = c(0,50,100,150)) + coord_flip()
plot3 + scale_fill_manual(breaks = c("Skews Right", "Skews Left", "Middle"), 
                       values=c("#8b2832", "#3c5d5b", "#d1a343"))+ xlab("Sources")
```

